name: UI Automation CI with Allure Report

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Tests
        run: mvn clean test

      - name: Install Allure
        run: |
          sudo apt-add-repository ppa:qameta/allure
          sudo apt-get update
          sudo apt-get install allure -y

      - name: Generate Allure Report
        run: allure generate target/allure-results --clean -o allure-report

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report